FROM nvidia/cuda:9.0-cudnn7-devel

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential curl git pkg-config apt-utils\
                                               python3 python3-dev python3-pip python3-setuptools cmake

RUN apt-get install -y libjpeg-dev libtiff-dev libjasper-dev libpng-dev \
                       libavcodec-dev libavformat-dev libswscale-dev \
                       libv4l-dev libatlas-base-dev gfortran libx264-dev

RUN pip3 install --upgrade pip
RUN pip3 install tensorflow-gpu==1.10.0 keras==2.2.0 pandas h5py flask imagehash==3.4 numpy==1.14.0 matplotlib Pillow scikit-learn jupyter jupyter-tensorboard

WORKDIR /tapple_prof

# COPY requirements.txt /tapple_prof/requirements.txt
# RUN pip install -r requirements.txt

EXPOSE 8888
COPY . /tapple_prof
